### PR TITLE
Fix OS detection and download OS-native archive extension

### LINKED ISSUE #111: Bug: Amd64 installed instead of arm
### What happened?

Hi,

We use a github runner based on arm64 in aws, and when we start using this action, we got a strange error:

```
Helm tool version: 'v3.11.3' has been cached at *_tool/helm/3.11.3/arm64/linux-amd64/helm
```
It's looks like that actions is downloading the incorrect version according to my architecture:

```
uname -m
aarch64
```

Native script get_helm.sh is working as shine, so it's looks there is a problem in node-script:

```
   const arch = os.arch()
   const operatingSystem = os.type()

   switch (true) {
      case operatingSystem == LINUX && arch == ARM64:
         return util.format(
            'https://get.helm.sh/helm-%s-linux-arm64.zip',
            version
         )
```

not sure if the os.arch is returning in this case aarch64 instead of arm64, so the condition in switch is incorrect.

### Version

- [X] I am using the latest version

### Runner

self-hosted, linux, arm64 (graviton aws)

### Relevant log output

Helm tool version: 'v3.11.3' has been cached at *_tool/helm/3.11.3/arm64/linux-amd64/helm
....
_tool/helm/3.11.3/arm64/linux-amd64/helm: cannot execute binary file: Exec format error

### LINKED ISSUE #119: Bug: unzip not available on ARC runners with default image
### What happened?

Hello!

When using GitHub's Actions Runner Controller with the default runner image, the `Azure/setup-helm` action fails due to `unzip` being unavailable. It is necessary to `sudo apt update && sudo apt install unzip` prior to using this action.

It seems sensible for `Azure/setup-helm` to check for the presence of its dependencies and install them when they're unavailable.

### Version

- [X] I am using the latest version

### Runner

self hosted, default ubuntu-based image

### Relevant log output

```
Run azure/setup-helm@v3
  with:
    version: v[3](https://github.com/tay-bird/nightshade/actions/runs/7558790943/job/20581132748#step:4:3).13.3
Downloading v3.13.3
  Error: Error: Unable to locate executable file: unzip. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

### PR DESCRIPTION
**Pull request by bonddim**
- Switch from `os.type()` to `os.platform()`
- Download `tar.gz` archives on non-Windows platforms

Fixes #111 
Fixes #119

### CODE REVIEW

**Comment by bonddim** [comment]
@OliverMKing , @davidgamero 
pls, review

**Review by davidgamero — APPROVED** [review]
lgtm thanks for the improvement!

**Comment by bonddim** [comment]
@bfoley13 , maybe you can review?

**Review by jaiveerk — APPROVED** [review]

**Comment by cheskayang** [comment]
thx for this fix, when do you think this can be merged and released?

**Comment by davidgamero** [comment]
releasing in #134

**Pull request merged**
